spring:
  application:
    name: spring-cloud-zipkin-zdb
  zipkin:
    base-url: http://localhost:9411

server:
  port: 36003

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/